### ISSUE TITLE
Add egypt and south sudan to 2scale

### ISSUE THREAD

**Issue by joycarpediem** [akvo/2scale#3]
It should come up in the map view in the home page

**Comment by dedenbangkit** [comment]
For now, let's add them to the test until we finish the new view Model @wayangalihpratama, this required re-seed data from the beginning because we need to update the cascade version in DB.
- [ ] Update cascade version in config.
- [ ] Reseed test.

**Comment by wayangalihpratama** [comment]
Try to reseed on my local and working fine
